version: '3.4'
services:
  flyway:
    image: 'flyway/flyway:latest'
    env_file:
      - .env-dev
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./app/src/main/resources/db/migration/postgres:/flyway/sql
  nginx:
    image: "registry.digitalocean.com/postraves-registry/postraves-nginx-dev:latest"
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - flyway
  api:
    image: "registry.digitalocean.com/postraves-registry/postraves-wiki-api-dev:latest"
    hostname: api
    env_file:
      - .env-dev
    depends_on:
      - flyway
