version: '3.4'
services:
  flyway:
    image: 'flyway/flyway:latest'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: -url=jdbc:postgresql://postgres:5432/postraves -schemas=public -user=${POSTGRES_USERNAME} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./app/src/main/resources/db/migration/postgres:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=postraves
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USERNAME}", "-d", "postraves" ]
      interval: 5s
      timeout: 1s
      retries: 2
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    container_name:
      api_container
    build:
      context: ./app
      dockerfile: Dockerfile
      target: final
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase_admin_creds
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - firebase_admin_creds
    depends_on:
      - postgres
      - redis
secrets:
  firebase_admin_creds:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}
