spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    devtools:
      restart:
        poll-interval: 2s
        quiet-period: 1s
    flyway:
      locations: classpath:/db/migration/postgres
    profiles:
      active: test
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${LOCAL_PG_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postraves
    username: mmazurovsky
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: baeldung
#    key-store: classpath:keystore/baeldung.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#security:
#  firebase-props:
#    enable-strict-server-session: false
#    enable-check-session-revoked: false
#    enable-logout-everywhere: false
#    session-expiry-in-days: 5
#  cookie-props:
#    max-age-in-minutes: 7200
#    http-only: true
#    secure: true
#    domain: ${DOMAIN}
#    path: /
#  allow-credentials: true
#  allowed-origins:
#    - https://${DOMAIN}
#    - http://localhost:3000
#  allowed-methods:
#    - GET
#    - POST
#    - PUT
#    - PATCH
#    - DELETE
#    - OPTIONS
#  allowed-headers:
#    - Authorization
#    - Origin
#    - Content-Type
#    - Accept
#    - Accept-Encoding
#    - Accept-Language
#    - Access-Control-Allow-Origin
#    - Access-Control-Allow-Headers
#    - Access-Control-Request-Method
#    - X-Requested-With
#    - X-Auth-Token
#    - X-Xsrf-Token
#    - Cache-Control
#    - Id-Token
#  allowed-public-apis:
#    - /favicon.ico
#    - /session/login
#    - /event/public/**
#    - /artist/public/**
#    - /unity/public/**
#    - /place/public/**
#    - /common/public/**
#    - /user/public/**
#    - /country/public/**
#    - /city/public/**
#  exposed-headers:
#    - X-Xsrf-Token
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:testdb
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
---