version: '3.4'
services:
  api:
    container_name:
      solo_api_container
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - firebase_admin_creds
secrets:
  firebase_admin_creds:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}
