version: '3.4'
services:
  api:
    container_name:
      solo_api_container
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
