version: '3.4'
services:
  api:
    image: "${DEV_WIKI_API_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
