FROM gradle:jdk11 AS builderrr
ENV POSTGRES_HOST=${POSTGRES_HOST}, POSTGRES_USERNAME=${POSTGRES_USERNAME}, POSTGRES_PASSWORD=${POSTGRES_PASSWORD}, REDIS_HOST=${REDIS_HOST}
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
CMD gradle build --no-daemon

FROM adoptopenjdk/openjdk11:alpine
EXPOSE 8443
ENV POSTGRES_HOST=${POSTGRES_HOST}, POSTGRES_USERNAME=${POSTGRES_USERNAME}, POSTGRES_PASSWORD=${POSTGRES_PASSWORD}, REDIS_HOST=${REDIS_HOST}
VOLUME /tmp
WORKDIR /app
COPY --from=builderrr /home/gradle/src/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/app/app.jar"]
