upstream api {
  server api:8080;
}

map $http_user_agent $ignore_ua {
    default                 0;
    "~Pingdom.*"            1;
    "ELB-HealthChecker/2.0" 1;
}

server {
  listen 80;
  listen 443 ssl;

  # Redirect non-https traffic to https
  if ($scheme != "https") {
      return 301 https://$host$request_uri;
  } # managed by Certbot

  # RSA certificate
  ssl_certificate /etc/letsencrypt/live/postraves.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/postraves.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
#   ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot



  location /api/ {
    proxy_pass http://api/;
    if ($ignore_ua) {
        access_log off;
        return 200;
    }
  }
}