upstream api {
  server api:8080;
}

map $http_user_agent $ignore_ua {
    default                 0;
    "~Pingdom.*"            1;
    "ELB-HealthChecker/2.0" 1;
}

server {
  listen 80;

  location /api/ {
    proxy_pass http://api/;
    if ($ignore_ua) {
        access_log off;
        return 200;
    }
  }
}