upstream api {
  server api:8080;
}

map $http_user_agent $ignore_ua {
    default                 1;
    "ELB-HealthChecker/2.0" 0;
}

server {
  listen 80;

  location /api/ {
    proxy_pass http://api/;
    access_log /var/log/nginx/access.log combined if=$ignore_ua;
  }
}